env:
  global:
    secure: "L+fCrv4P21Hgx2B7n4OFZnzf/JGQlUO7SYHuF0/HJ16hk5a7rxpH6pAidS3SSskWfgMK/al8Tuf3YbOXgsLbHeLaDvMHuaHWdNAycJkUpMFbiBqNwyMCvnbAxRK8V9ifkNIfHaUOBrAAvUsyFFmBB1mlljhqpebp90xbJNvTHdIj++cRj4RWDs9XenCtqwds7tuObLnyiwF1wz3ukfdWZAxbb0R1cSyjwnSW1W7ws7ZBDM9uS2cNuRIJJHbjfYMizNrDFgSSS9TgjtvRQQD1ZgAziBmRqU58Ph4zUhXujGaf/tRdHYOoevZYPM2TkmvJ1K1s4Gp3Dc6iq30WYHoNsfFu8oMPwzTgy29q6w5TjmH8o7TF9k7w1iElJE74Hze4jEXAvyzRkVxsRvt/UTJZ/bIYJH9Ry1Smy2MUqun14uwVAg+rZ/X8vr++VqZjCWWzS/xb9y9lj6KC8Rtmgp0J53kw2vAUR9bmvR9yGG7pce3CoLdpDKsTOme54Bwu/DB+EpaT6ju/qwG8YShGYZ42nM6ZUAnXhW+4PwpjfajryE1NiSwnr4wYB051vINlQ8bYpjDc+YPVNcjOzzmsN6+EQKWqn828JSx8wT2RYVfh7HrsNKINjQSYEfNBetcfXM5EsXcLeQak+M4A9Fi6tsZkXTLiQNR/XwuhX3C//5KznDA="

addons:
  coverity_scan:

    project:
      name: PhoenixOrg/PhoenixEngine
      version: 1.0
      description: PhoenixEngine

    notification_email: mitchdandrews@gmail.com

    build_command_prepend: brew install glfw3 glew

    build_command: xcodebuild -workspace Solution/PhoenixEngine.xcworkspace -scheme TestGame -sdk macosx ONLY_ACTIVE_ARCH=NO

language: objective-c

compiler:
- gcc
osx_image: xcode6.4

install: brew install glfw3 glew

branches:
  only:
  - master

notifications:
  email:
  - mitchdandrews@gmail.com

sudo: required

script: xcodebuild -workspace Solution/PhoenixEngine.xcworkspace -scheme TestGame -sdk macosx ONLY_ACTIVE_ARCH=NO

os:
- linux
