language: objective-c

xcode_project: Solution/PhoenixEngine.xcworkspace
xcode_scheme: TestGame

compiler:
  - gcc

osx_image: xcode6.4

install: make get-deps

branches:
  only:
    - master

notifications:
  email: 
    - mitchdandrews@gmail.com

sudo: required

script:
  - make -C Solution config=debug

os: 
  - linux
