
language: objective-c

compiler:
- gcc

osx_image: xcode6.4

branches:
  only:
  - master

install: brew install glfw3 glew

script: xcodebuild -workspace Solution/PhoenixEngine.xcworkspace -scheme Game -sdk macosx ARCHS=i386 ONLY_ACTIVE_ARCH=NO

notifications:
  email:
  - mitchdandrews@gmail.com