language: cpp

compiler:
  - gcc
  - clang

install:
  - sudo apt-get install -qq libXmu-dev libXi-dev glew-utils dos2unix git wget 
branches:
  only:
    - master

notifications:
  email: 
    - mitchdandrews@gmail.com

sudo: required

script:
  - make -C Solution config=release

os: 
  - linux
