language: cpp

compiler:
  - gcc
  - clang

install:
  - sudo apt-get install -qq libXmu-dev libXi-dev libgl-dev dos2unix git wget glfw3 
branches:
  only:
    - master

notifications:
  email: 
    - mitchdandrews@gmail.com

sudo: required

script:
  - make -C Solution config=release

os: 
  - linux
