language: cpp

compiler:
  - gcc
  - clang

install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install gcc-4.7 g++-4.7
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.7 40 --slave /usr/bin/g++ g++ /usr/bin/g++-4.7
  - gcc --version && g++ --version
  
branches:
  only:
    - master

notifications:
  email: 
    - mitchdandrews@gmail.com

sudo: required

script:
  - make -C Solution config=release

os: 
  - linux