language: cpp

compiler:
  - gcc
  - clang

install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq		
  - sudo apt-get install -qq gcc-5 g++-5		
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 40 --slave /usr/bin/g++ g++ /usr/bin/g++-5		
  - export CXX="g++-5" CC="gcc-5"		
  - gcc --version && g++ --version
  - sudo apt-get install -qq libXmu-dev libXi-dev glew-utils dos2unix git wget aptitude
  - aptitude search glfw
  - aptitude search glew
  - sudo apt-get install -qq libglew-dev libglfw-dev

branches:
  only:
    - master

notifications:
  email: 
    - mitchdandrews@gmail.com

sudo: required

script:
  - make -C Solution config=release

os: 
  - linux
