language: objective-c

compiler:
  - gcc

osx_image: xcode6.4

install: brew install glfw3 glew

branches:
  only:
    - master

notifications:
  email: 
    - mitchdandrews@gmail.com

sudo: required

script: xcodebuild -workspace Solution/PhoenixEngine.xcworkspace -scheme TestGame -sdk macosx ONLY_ACTIVE_ARCH=NO


os: 
  - linux
